//import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";

//const geistSans = Geist({
  //variable: "--font-geist-sans",
//  subsets: ["latin"],
//});

//const geistMono = Geist_Mono({
//  variable: "--font-geist-mono",
//  subsets: ["latin"],
//});

//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

//export default function RootLayout({
//  children,
//}: Readonly<{
//  children: React.ReactNode;
//}>) {
//  return (
//    <html
//      lang="en"
//      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//   >
//      <body className="min-h-full flex flex-col">{children}</body>
//    </html>
//  );
//}

//import { ClerkProvider } from "@clerk/nextjs";

//export default function RootLayout({
//  children,
//}: {
//  children: React.ReactNode;
//}) {
//  return (
//    <html lang="en">
//      <body>
//        <ClerkProvider>
//          {children}
//        </ClerkProvider>
//      </body>
//    </html>
//  );
//}

import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'HireIQ',
  description: 'AI-Powered Recruitment Platform',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}